name: UploadOSS
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: yarn 
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: "oss-cn-shenzhen.aliyuncs.com"
        access-key-id: ${{secrets.AccessKey_ID}}
        access-key-secret: ${{ secrets.AccessKey_Secret }}
    - name: Install and Build
      run: |
        yarn install
        yarn build 
    - name: Upload
      run: ossutil cp ./build oss://puqingdash/ -rf
